package config

import "time"

const (
	VERSION_STRING = "v1.3.5"

	SPINER_INDEX    = 9
	SPINER_DURATION = 77 * time.Millisecond

	REPOSITORY = "https://github.com/suryakoinworks/kw-migrate.git"

	CONFIG_FILE = "Kmtfile.yml"

	CREATE_TABLE = "CREATE TABLE"

	CREATE_SEQUENCE = "CREATE SEQUENCE"

	CREATE_INDEX = "CREATE INDEX"

	SECURE_CREATE_TABLE = "CREATE TABLE IF NOT EXISTS"

	SECURE_CREATE_SEQUENCE = "CREATE SEQUENCE IF NOT EXISTS"

	SECURE_CREATE_INDEX = "CREATE INDEX IF NOT EXISTS"
)
